spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-microservice
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/user-microservice/**
        - id: map-microservice
          uri: lb://MAP-MICROSERVICE
          predicates:
            - Path=/map-microservice/**
        - id: scooter-microservice
          uri: lb://SCOOTER-MICROSERVICE
          predicates:
            - Path=/scooter-microservice/**
        - id: admin-microservice
          uri: lb://ADMIN-MICROSERVICE
          predicates:
            - Path=/admin-microservice/**
        - id: trip-microservice
          uri: lb://TRIP-MICROSERVICE
          predicates:
            - Path=/trip-microservice/**
        - id: report-microservice
          uri: lb://REPORT-MICROSERVICE
          predicates:
            - Path=/report-microservice/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8765