spring:
  application:
    name: map-microservice

  datasource:
    url: jdbc:h2:mem:db-map
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8088